In [0]:
class SparseMatrix:

    def __init__(self, m, n):
        self.s = [[m, n, 0]]
        self.m = m
        self.n = n
        
    def append(self,i,j,val):
        if val != 0: 
            self.s.append([i,j,val])
        self.s[0][2] = len(self.s) - 1
    
    def shape(self):
        return (self.m, self.n)
    
    def getValue(self, i, j):
        for k in range(1,len(self.s)):
            if self.s[k][0] == i and self.s[k][1] == j:
                return self.s[k][2]
        return 0
            
    def print(self):
        import numpy as np
        _tmp = np.zeros((self.m, self.n))
        for i in range(1,len(self.s)):
            _tmp[self.s[i][0]-1,self.s[i][1]-1] = self.s[i][2]
        print(_tmp)

    def transpose(self):
        pass
        
    @classmethod
    def mult(cls, a, b):
        if a.n != b.m:
            return -1
        c = SparseMatrix(a.m, b.n)
        for i in range(1, a.m+1):
            for j in range(1, b.n+1):
                summ = 0
                for k in range(1, a.n+1):
                    summ += a.getValue(i,k) * b.getValue(k,j)
                if summ != 0:
                    c.append(i, j, summ)
        return c

a = SparseMatrix(3,3)
b = SparseMatrix(3,3)

a.append(1,1,1)
a.append(2,2,2)
a.append(3,3,3)
b.append(1,1,4)
b.append(1,2,7)
b.append(2,3,2)
b.append(3,3,1)

a.print()
b.print()

c = SparseMatrix.mult(a, b)
c.print()  

[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]
[[4. 7. 0.]
 [0. 0. 2.]
 [0. 0. 1.]]
[[4. 7. 0.]
 [0. 0. 4.]
 [0. 0. 3.]]
